image: spacecowboy/android-docker-builder:24

#variables:
#  ANDROID_TARGET_SDK: "24"

before_script:
  - chmod +x ./gradlew

build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

test:
  script:
    - ./gradlew check
  artifacts:
